name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest # VM

    services:
      # spin up PostgreSQL container for tests
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: taskdb
          POSTGRES_USER: taskuser
          POSTGRES_PASSWORD: taskpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U taskuser -d taskdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # pre-built GitHub action that clones repo into VM

      - name: Set up Java 17
        uses: actions/setup-java@v4 # installs Java
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven" # cache dependencies

      - name: Build and test
        env:
          DB_URL: jdbc:postgresql://localhost:5432/taskdb
          DB_USERNAME: taskuser
          DB_PASSWORD: taskpass
        run: ./mvnw clean verify

      - name: Build Docker image
        run: docker build -t task-service:${{ github.sha }} ./task-service # tag image with commit hash
